metadata:
  name: spring-boot-hello-prod
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/raycon300/app-service-gitops-prod
    targetRevision: HEAD