apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  project: default
  syncPolicy:
    automated: {}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.spec.destination.namespace }}
  source:
    path: oc-manifests
    repoURL: {{ .Values.spec.source.repoURL }}