apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-boot-hello-prod
  namespace: openshift-gitops
spec:
  project: default
  syncPolicy:
    automated: {}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: spring-boot-prod
  source:
    path: spring-boot-hello
    repoURL: {{ .Values.spec.source.repoURL }}