{{- if .Values.app.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Values.app.vpa.name }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "argocd.defaultLabels" . | indent 4 }}
    app: {{ .Values.app.name }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment 
    name:       {{ .Values.app.deploymentName }}
  updatePolicy:
    updateMode: "Off"
{{- end }}